kind: Secret
apiVersion: v1
metadata:
    name: signing-secrets
    labels:
        app.kubernetes.io/component: chains
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
        pipeline.tekton.dev/release: devel
        version: v0.6.1
data:
    cosign.key: ENC[AES256_GCM,data:0K+wG43NLg14o//ea22IiU8Yu/qDWgkqCTFtpM8+hU2e1gS+4oyESEantMZvNF9fDeACfksj77IL2pqkTRiZntSXcQisUczfWNiPXRtG5Z3aJMRkR5c18QHAcEGtuwtm5n+tqwQqvRndkF8iJZ0X5/kG0FrE+CDDnGRhl9Pp8U3sLaD0xPldM7UGKJMm3vmtZjhBGj8kZM+rQ9H8+3BzVBWKpavD9OdIuZhzC23DhTTk6xT/ZOebpKUX9yL6Fi908S3/CJvyHDIx4evvnP6Ju3ZJPdXQFXC8b8aO8RTVskaQTXKzmRgeLqdEr95IPlZ/aSg4wG827hcGEk/JzcyU71T06XNuvCHaE9S4TnjS7V3PJ82555/xOonx67cTAwQ3RXuMW4dW7J9/y/m+OUdUszu//oGHEAkCzQIEqn9TMg8Nn9up6Bd/puHfIQkBBK2ZPecEAUcm9pMV5U2PGB+0Hh01sryfAEhwi6WFJrB2iqVcrwUx1C29hw86cgHoiGcfo4uU+MyKvb2zx2evkc0Pb73Khai99uCFoEgl0DZ+jYYdLm7AhnWqv5uWfa+VnZDo4Sz11WOOknA9v5YIDxl+KKyFRSpBsOklysDfCUlPmrFcrN/NgUQShxldij2nvZIhQ8nY+XwfzQmhOoJ4u3NgEdwJURbuvKKN4P4l6znLYLaU/sN4oGw+wvOWgK4kW0Zi5jyHuZxTY8kZzHh477ic/FTyl4itRwqJfe2o6LmkGHRD2reUNlsJtOvStC+WQJPUp80DjmI9kR29G93YplKCWj877tr1WFO0NiAXsXLkBdqEwHjZF0IrcxzjXNfT4cJWHcahl5lsgAWhzInNO0f88jonZRAtDDQTsq30y2ifwcX99kkDa+gsNxlURvMaz1s+V94BMK+/0jT0itVbTWcHWo8udFei/xbbseSfgPwqF2K8hRYScJ91qDkxm6GC1bTWuvB97kM76cEiNtl1Qq8x15DM/OOSYgw7dbIFypn0vQPYG6Pj4o3vBrT+Fq4ZpYSgYJZclEA7Vzk92gLO/4Ppqo2ZjG+KMuc5WXvXAN/kqc1pPUa578+UQ2GoHUCSbkEYlVS7f4KARsT/NTllIYBs4SkguVGKKUI9LvKbSVLFXZhTXhZuREFyk1gPekBW7xq0/GeTog==,iv:eCoK77RG92ysHSiwSJFurPmwOosjXJgEPBhRrjsvsdA=,tag:QkFoXfRs4DMtXryhV3VG9g==,type:str]
    cosign.password: ENC[AES256_GCM,data:GWKgj7fvoVUt7HsH,iv:b7So2Y1qdI/+DUiGOLEv0beR3WCAFmfsf3bOYHBmVZ8=,tag:s2toyznwBxlzMmA7RHJQHQ==,type:str]
    cosign.pub: ENC[AES256_GCM,data:S+JwC83q04DWZdmRWxHN7DwBJ1buqyZSy81RhwagYhmwWyPmPvwNE/MXJMIHoPIeVfcBYZqw2vNnN4lAGcPlUgqp6QnK6x7OCR4yb+PzQBupXtQ0V4QUbg0YP72a8udKK21VorvSHHRKoDucxexw47F+S0tB7N/loqdfIgkTjN3kxM7KPtVXAGQ+esnQk38ld0IapgaAqv3Ab+RQez8ZGox2SCu7nrxryL/7WTx8crWI5f9EbU+6zv1f4w26QbErIJ3hE+gKrmGkrVbi0sysbSZyEkg0bbrv8/1GpdyifLONZ5ShMI0FgDjyuC2/Qo46,iv:TtAPmqiLuC1KsPho/vVm7Pl2eRh44EmP6rHZ4TfDPKI=,tag:4NDHuuPAo91imI4oe+SLKQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-02-23T21:09:46Z'
    mac: ENC[AES256_GCM,data:bg/nGB895wYgbOg0SsKIHD9opFTPLJ0aofKM85IlWztISW4AUh7J09FIWVT4XqaZRgS9tPdmfpA83jO+8Ty5qU8lxXw/GvIW4rTe8UCcAqODd+0nG/DFE44NnAHQ6QUPzOwtvkD842wt8IP0N+4+MQbW30o+qZ8TBl1neiaDLHY=,iv:hZJcZaS5MvhLwR1yQqRd+s6YETCqjVgBdC/JPMMECto=,tag:of+/jgi1y/vhdROLrg7oeQ==,type:str]
    pgp:
    -   created_at: '2022-02-23T21:09:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//U4nHyYlO7PYUi3KR+5WsUM50fi+Sccs9GlCbXNg/rKio
            7SYjIJ+EjQ/w7WX2y5JQSPBC6OisW9AvEYN+pRZch8zHBb2XA/Bcclrv0YxnhFFN
            GHspqQCgt8I7V+XFWo8KKADXqZD4JKQgUm2TWuf7mrjbbi9+mqDHUROwfLbwTKYL
            hOagdHija5yIA2/Bb9bwp3T450tHX7aLggJSvn5KshoSzXKEZP3wBx9s2J0JZAOp
            121P1IohBaIsXjK4spLWom5zPsW0qePor/aVuBNh8+I43RKS3N4gGTLc6lTjFVcG
            MgRfB9j8lMbkxli96Vt6GKL5Fta0ZBoJdOHm1PJPAWTn2zqH6fjDh7yZaBtr415+
            9rsLqpyTRnozR4aFhbzd4G+JbaIQHpt9HgBqhR7sBnyiyUrzqG7LlgJyk1lZSnr9
            zw1KT1+pV4h+yvBbHy5paH//KdRnnKn69KFhZYCTLAVvUwf2R2oD5YYz9iL/BhKQ
            8Kbuuf/gUZYE7KL0qSbVD2c7s2Lg5kgU1rVFcCeANzuPYqtCfPG3sTDY1xDLjBAK
            SFMq5Uy/1U+5IxImNtlQCstKnIVvLGkgjz+cnrnCTkTTCaCm7+QDChAIDlTTLlhb
            9lYMkmS5Evmv2sZoiiUWOooVlSM3j4bwCKS6n+m1mMreyXjJP1IVmgfVhfNHLa3S
            XAFWhLZqQ6kgLtFR4AaYLXE+g0NXubfviDnPGe+WfxuyIpnaTIUkrtuiHjRFy3Tu
            gIXy1N4ZGmWAh0/OIpTYSPq79EEP0eeD+7P+LClmfK+mbJdrYZ8yhF7K/Cwl
            =coBO
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    -   created_at: '2022-02-23T21:09:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf/SFc3wamvWSQVGjZRNwf0OGcNKaZliDivI1r4yeAascz/
            Jv4t/0BfauyamoW0zmcxF3O6Gu3nj9heAA26LC+tP3+A/Swp+rTM+JrEj63pM7RR
            mheR6gOTACwzJHnGl0HHEBnCCVRQh9IAdVDP3iSElPxEJrGEbvKDXBDmHC0D1/CF
            Wmkrqcwe6tRmv4g2G4so89D9m5AO/OMQyG4GvJz74J2C7xcy4DzOFrSUIkezIyTV
            earnUd89X8vhVOC/KHCkfoLH3+fyqspQ+24nauqXMpd5r9azKPrbGSfewsgPLfU0
            zk+NgHxF9OYdRm47hcj21Ao4Ia38VTy97dw2LdhXxtJcAfBcg9risfcp583o7uvR
            fR4Wfe7irp7IwklhYo5CpNtoGDMGJOMmjK+tl4cTgnb9sOTR8GO/nq0AHvOR42hn
            /Uf/KhU3Azb6lrKZrtVMjQx2od3elGMbO5ZmFOo=
            =vT4M
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
