---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: "devel"
    version: "v0.6.1"
data:
  artifacts.oci.storage: oci
  artifacts.taskrun.format: tekton
  artifacts.taskrun.storage: tekton
  transparency.enabled: 'true'
