apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- chains-config.yaml
- config-logging.yaml
- signing-secrets.yaml
- tekton-chains-controller.yaml
- chains-anyuid-rolebinding.yaml
