---
apiVersion: v1
kind: Secret
metadata:
  name: signing-secrets
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: "devel"
    version: "v0.6.1"
