---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-chains-controller
  labels:
    app.kubernetes.io/name: tekton-pipelines
    app.kubernetes.io/component: chains
    pipeline.tekton.dev/release: "devel"
    version: "v0.6.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-chains-controller
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: tekton-chains-controller
        app.kubernetes.io/name: tekton-pipelines
        app.kubernetes.io/component: controller
        # # tekton.dev/release value replaced with inputs.params.versionTag in pipeline/tekton/publish.yaml
        # pipeline.tekton.dev/release: "devel"
        version: "v0.6.1"
    spec:
      serviceAccountName: tekton-chains-controller
      containers:
        - name: tekton-chains-controller
          image: gcr.io/tekton-releases/github.com/tektoncd/chains/cmd/controller:v0.6.1@sha256:8faf79b4bf92078feb4b3b5229eeccc19a32512f847abc95c109d37842cb51f3
          volumeMounts:
            - name: signing-secrets
              mountPath: /etc/signing-secrets
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_DOMAIN
              value: tekton.dev/chains
      securityContext:
        runAsUser: 0
      volumes:
        - name: signing-secrets
          secret:
            secretName: signing-secrets
